/**
 * Class model
 *
 * @description An instance of a course. This represents the available sections of a course, what time to meet, where to meet, what section number it is.
 *
 * @fileoverview Database operations for class using PostgreSQL
 * A course is comprised of:
 * - The class number (also it's primary key)
 * - The course it represents
 * - Class meeting start time
 * - Class meeting end time
 * - Class meeting days
 * 	- Represented as an array of texts that could be: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday
 * - Instructor
 *
 */
const { query } = require("../config/database");

/**
 * The following are type declarations for relevant objects to add clarity. They do not affect the syntax of the code and are only for documentation
 *
 * @typedef {{courseId: number,location: string,startTime: string,endTime: string,daysOfWeek: string[],maxSeats: number,availableSeats: number,maxWait: number,availableWaitList: number}} Class
 * @typedef {{id: number, meeting_location: string, start_time: string, end_time: string, days_of_week: string[] subject: string, number: number, credit: number}} ClassFE What frontend sees
 * */

/**
 * @description Attempts to initialize the classes table.
 *
 */
async function createTable() {
	// Note the current set up allows for duplicate classes with the same time and days if the location is null
  await query(`
      CREATE TABLE IF NOT EXISTS classes (
        id SERIAL PRIMARY KEY,
				course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
				meeting_location VARCHAR(30),
				start_time TIME NOT NULL,
				end_time TIME NOT NULL,
				days_of_week TEXT[] NOT NULL,
				max_seat INTEGER,
				available_seat INTEGER,
				max_wait_list INTEGER,
				available_wait_list INTEGER,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
				UNIQUE(course_id, meeting_location, start_time, end_time, days_of_week)
      )
  `);
}

/**
 *
 * @param {Class} newClass
 * @returns
 */
async function add(newClass) {
  const { courseId, location, startTime, endTime, daysOfWeek, maxSeats, maxWait } = newClass;

  try {
    const result = await query(
      `INSERT INTO classes (course_id, meeting_location, start_time, end_time, days_of_week, max_seat, available_seat, max_wait_list, available_wait_list)
			VALUES ($1, $2, $3, $4, $5, $6, $6, $7, $7)
			RETURNING id, course_id, meeting_location, start_time, end_time, days_of_week, max_seat, available_seat, max_wait_list, available_wait_list`,
      [courseId, location, startTime, endTime, daysOfWeek, maxSeats, maxWait]
    );
    return result.rows[0];
  } catch (error) {
    console.error("Error inserting class: \n", error);
    throw error;
  }
}

/**
 *
 * @param {number} classId
 * @returns {Promise<Class>} The class from the id
 */
async function getById(classId) {
  try {
    const result = await query(
      `SELECT 
        c.id, 
        c.meeting_location, 
        c.start_time, 
        c.end_time, 
        c.days_of_week,
        c.max_seat,
        c.available_seat,
        c.max_wait_list,
        c.available_wait_list,
        co.id as course_id,
        co.subject,
        co.number,
        co.credit
       FROM classes c
       JOIN courses co ON c.course_id = co.id
       WHERE c.id = $1`,
      [classId]
    );
    return result.rows[0];
  } catch (error) {
    console.error("Error getting class: \n", error);
    throw error;
  }
}

/**
 * @description Get all classes at the inputted page and inputted max class count per page
 * @param {number} page Page number (default: 1)
 * @param {number} limit Number of items per page (default: 10)
 * @returns {Promise<{classes: Class[], total: number, page: number, pages: number}>} Paginated classes with metadata
 */
async function getClasses(page = 1, limit = 10) {
  try {
    // Some of the following code was generated by Claude Haiku 4.5

    // Ensure page and limit are positive integers
    page = Math.max(1, parseInt(page) || 1);
    limit = Math.max(1, Math.min(100, parseInt(limit) || 10)); // Max 100 per page

    const offset = (page - 1) * limit;

    // Get total count
    const countResult = await query(`SELECT COUNT(*) as total FROM classes`);
    const total = parseInt(countResult.rows[0].total);
    const pages = Math.ceil(total / limit);

    // Get paginated classes
    const result = await query(
      `SELECT 
        c.id, 
        c.meeting_location, 
        c.start_time, 
        c.end_time, 
        c.days_of_week,
        c.max_seat,
        c.available_seat,
        c.max_wait_list,
        c.available_wait_list,
        co.id as course_id,
        co.subject,
        co.number,
        co.credit
       FROM classes c
       JOIN courses co ON c.course_id = co.id
       ORDER BY co.subject, co.number, c.start_time
       LIMIT $1 OFFSET $2`,
      [limit, offset]
    );

    return {
      classes: result.rows,
      total,
      page,
      pages,
      hasNextPage: page < pages,
      hasPrevPage: page > 1,
    };
  } catch (error) {
    console.error("Error getting classes: \n", error);
    throw error;
  }
}

module.exports = { createTable, add, getById, getClasses };
